name = "spi_generic"
description = "Generic SPI interface for bare-metal Ada"
version = "0.1.0-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
machine_types = "*"

[[pins]]
machine_types = { url = "https://github.com/GNAT-Academic-Program/machine_types.git", branch = "main" }